config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup',to: 'users#new'
  resources :users, except: [:index]
  resources :decks do
   resources :favorites, only: [:index, :create, :destroy]
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  mount_uploader :imagefile_name, ImageUploader
  
  def decks
    return Deck.where(user_id: self.id)
  end
  
  has_many :decks, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_decks, through: :favorites, source: :deck
  
  def favorited?(deck)
    self.favorites.exists?(deck_id: deck.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:edit, :show]
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  
  def show
    @user = User.find_by(id: params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    @user.imagefile_name = "default_user.png"
    if @user.save
      flash[:success] = "ユーザー登録が完了しました"
      session[:user_id] = @user.id
      redirect_to root_url
    else
      render("users/new")
    end
  end
  
  def edit
    @user = User.find_by(id: params[:id])
  end
  
  def update
    @user = User.find_by(id: params[:id])
    if @user.update(user_params)
      flash[:success] = 'ユーザー編集が完了しました'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザー編集に失敗しました'
      render :edit
    end
  end
  
  def destroy
    @user = User.find_by(id: params[:id])
    @user.destroy
    
    flash[:success] = '正常に退会しました'
    redirect_to root_url
  end
  
  private
  
  def ensure_correct_user
    if current_user.id != params[:id].to_i
      flash[:danger] = "権限がありません"
      redirect_to root_url
    end
  end
  
  def user_params
    params.require(:user).permit(:name, :imagefile_name, :email, :password, :password_confirmation)
  end
  
  def logged_in?
    !!current_user
  end
  
end

app/views/users/edit.html.erb
<div class="row">
  <div class=" offset-lg-2 col-lg-8">
    <h1 class="mx-auto text-light font-weight-light mt-5 mb-3">ユーザー編集</h1>
  </div>
  <div class="bg-light offset-lg-2 col-lg-8 p-4">
    <% @user.errors.full_messages.each do |message| %>
      <div class="form-error alert alert-danger">
        <%= message %>
      </div>
    <% end %>
    <%= form_with(model: @user, local: true, multipart: true) do |f| %>
      <div class="form-group">
        <%= f.label :name, 'ユーザー名' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :imagefile_name, 'ユーザー画像' %>
        <%= f.file_field :imagefile_name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード確認' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      <%= f.submit '保存', class: 'btn btn-primary btn-block'  %>
    <% end %>
  </div>
</div>

app/views/users/login_form.html.erb
<div class="row">
    <div class="offset-2 col-8">
        <div class="mx-auto text-light font-weight-light h1 mt-5 mb-3">
          ログイン
        </div>
    </div>
    <div class="bg-light offset-2 col-8 p-4">
        <% if @error_message %>
          <div class="form-error">
            <%= @error_message %>
          </div>
        <% end %>
      <%= form_with(url: login_path, scope: :session, local: true)do |f| %>
            <div class="form-group">
              <%= f.label :email, 'メールアドレス' %>
              <input class="form-control" name="email" value="<%= @email %>">
            </div>
            <div class="form-group">
              <%= f.label :password, 'パスワード' %>
              <input type="password" name="password" class="form-control"value="<%= @password %>">
            </div>
            <input type="submit" class="btn btn-primary" value="ログイン">
      <% end %>
    </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="offset-lg-2 col-xs-8">
    <h1 class="mx-auto text-light font-weight-light  mt-5 mb-3">新規ユーザー登録</h1>
  </div>
  <div class="bg-light offset-lg-2 col-lg-8 p-4">
    <% @user.errors.full_messages.each do |message| %>
      <div class="form-error alert alert-danger">
        <%= message %>
      </div>
    <% end %>
    <%= form_with(model: @user, local: true) do |f| %>
      <div class="form-group">
        <%= f.label :name, 'ユーザー名' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード確認' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      <%= f.submit '新規登録', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
    <div class="col-lg-12 text-light">
        <img src="<%= "#{current_user.imagefile_name}" %>" class="mx-auto d-block rounded-circle bg-light userimage">
        <h2 class="text-center mt-5"><%= current_user.name %></h2>
        <p class="text-center mt-4"><%= current_user.email %></p>
    </div>
</div>
<div class="row">
    <div class="col-6 offset-lg-2 col-lg-4">
        <%= link_to("編集",edit_user_path(current_user),class: "btn btn-primary w-100 mx-auto d-block") %>
    </div>
    <div class="col-6 col-lg-4">
        <%= link_to '退会', @user, method: :delete, data: { confirm: '本当に退会してよろしいですか？' }, class: 'btn btn-danger w-100 mx-auto d-block' %>
    </div>
</div>