config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup',to: 'users#new'
  resources :users, except: [:index]
  resources :decks do
   resources :favorites, only: [:index, :create, :destroy]
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if logged_in?
      @decks = current_user.decks.order(id: :desc).page(params[:page]).per(10)
    end
  end

end

app/views/home/index.html.erb
<% if logged_in? %>
<div class="row">
  <div class="col-sm-12 col-lg-12 text-light">
    <img src="<%= "#{current_user.imagefile_name}" %>" class="mx-auto d-block rounded-circle bg-light userimage">
    <h2 class="text-center mt-5"><%= current_user.name %></h2>
  </div>
</div>
<div class="row">
  <div class="col-6 offset-lg-2 col-lg-4">
    <%= link_to("デッキ登録",new_deck_path(current_user),class: "btn btn-primary w-100 mx-auto d-block") %>
  </div>
  <div class="col-6 col-lg-4">
    <%= link_to("お気に入りデッキ一覧へ",deck_favorites_path(current_user), class: "btn btn-primary w-100 mx-auto d-block") %>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 mt-5">
    <%= paginate @decks %>
  </div>
</div>
<div class="row">
  <% @decks.each do |deck| %>
    <div class=" col-6 col-lg-2 mt-3">
      <%= link_to image_tag("#{deck.imagefile_name}", class: "cardimage"), deck_path(deck) %>
      <h5 class="text-center bg-light"><%= deck.name %></h5>
    </div>
  <% end %>
</div>
<div class="row">
  <div class="col-sm-12 mt-5">
    <%= paginate @decks %>
  </div>
</div>
<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>ようこそ！デッキ管理アプリ<br>List  for Cardgamerへ！！</h1>
      <%= link_to("アカウント作成", "signup", class: "btn btn-lg btn-primary" ) %>
      <%= link_to("ログイン", "login", class: "btn btn-lg btn-primary" ) %>
    </div>
  </div>
<% end %>