config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup',to: 'users#new'
  resources :users, except: [:index]
  resources :decks do
   resources :favorites, only: [:index, :create, :destroy]
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/deck.rb
class Deck < ApplicationRecord
  belongs_to :user
  
  validates :name, presence: true, length: { maximum: 15 }
  validates :comment, length: { maximum: 255 }
  validates :number_of_use, numericality: { only_integer: true }
  validates :number_of_wins, numericality: { only_integer: true }
  mount_uploader :imagefile_name, ImageUploader
  
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:edit, :update, :destroy]
  
  def new
    @deck = current_user.decks.build
  end
  
  def create
    @deck = current_user.decks.build(deck_params)
    if @deck.save then
      flash[:success] = 'デッキを登録しました。'
      redirect_to root_url
    else
      @decks = current_user.decks.order(id: :desc).page(params[:page])
      flash.now[:danger] = 'デッキの登録に失敗しました。'
      render new_deck_path
    end
  end
  
  def show
    @deck = current_user.decks.find_by(id: params[:id])
    @favorite = current_user.favorites.new
    wins = @deck.number_of_wins.to_i
    use = @deck.number_of_use.to_i
    if (wins == 0) || (use == 0) then
      @rate = 0
    elsif wins && use then
      @rate = wins.to_f / use.to_f * 100
    end
  end
  
  def edit
    @deck = current_user.decks.find_by(id: params[:id])
  end
  
  def update
    @deck = current_user.decks.find_by(id: params[:id])
    oldname = @deck.name
    oldimagefile_name = @deck.imagefile_name
    oldcomment = @deck.comment
    oldnumber_of_wins = @deck.number_of_wins.to_i
    oldnumber_of_use = @deck.number_of_use.to_i
    oldrate = oldnumber_of_wins.to_f / oldnumber_of_use.to_f * 100
    if @deck.update(deck_params) then
      if @deck.number_of_wins == oldnumber_of_wins.to_s && @deck.number_of_use == oldnumber_of_use.to_s
        if @deck.name == oldname && @deck.imagefile_name == oldimagefile_name && @deck.comment == oldcomment
          flash[:success] = '何も更新されませんでした。'
          redirect_to deck_path
        else
          flash[:success] = 'デッキ編集が完了しました。'
          redirect_to deck_path
        end
      else
        if @deck.number_of_wins.to_i < 0 || @deck.number_of_use.to_i < 0 then
          flash.now[:danger] = '正数を入力してください。'
          @deck.number_of_wins = oldnumber_of_wins.to_i
          @deck.number_of_use = oldnumber_of_use.to_i
          if (oldnumber_of_wins == 0) || (oldnumber_of_use == 0) then
            @deck.save
            @rate = 0
          else
            @deck.save
            @rate = oldrate
          end
          render action: :show
        elsif @deck.number_of_wins.to_i <= @deck.number_of_use.to_i then
          flash[:success] = '勝率を計算しました。'
          redirect_to deck_path
        elsif @deck.number_of_wins.to_i > @deck.number_of_use.to_i then
          flash.now[:danger] = '勝利回数は使用回数以下になるように入力してください。'
          @deck.number_of_wins = oldnumber_of_wins.to_i
          @deck.number_of_use = oldnumber_of_use.to_i
          if (oldnumber_of_wins == 0) || (oldnumber_of_use == 0) then
            @deck.save
            @rate = 0
          else
            @deck.save
            @rate = oldrate
          end
          render action: :show
        end
      end
    else
      if @deck.number_of_wins=="" || @deck.number_of_use=="" then 
        flash.now[:danger] = '数値を入力してください。'
          @deck.number_of_wins = oldnumber_of_wins.to_i
          @deck.number_of_use = oldnumber_of_use.to_i
          if (oldnumber_of_wins == 0) || (oldnumber_of_use == 0) then
            @rate = 0
          else
            @rate = oldrate
          end
        render action: :show
      elsif @deck.name == "" || @deck.name.length > 15 || @deck.comment.length > 255 then 
        flash.now[:danger] = 'デッキ編集に失敗しました。'
        render action: :edit
      elsif @deck.number_of_wins.to_i != /^[0-9]+$/ || @deck.number_of_use.to_i != /^[0-9]+$/ then
        flash.now[:danger] = '小数点と文字は入力しないでください。'
          @deck.number_of_wins = oldnumber_of_wins.to_i
          @deck.number_of_use = oldnumber_of_use.to_i
          if (oldnumber_of_wins == 0) || (oldnumber_of_use == 0) then
            @rate = 0
          else
            @rate = oldrate
          end
        render action: :show
      end
    end
  end
  
  
  def destroy
    @deck = current_user.decks.find_by(id: params[:id])
    @deck.destroy
    
    flash[:success] = 'デッキは正常に削除されました'
    redirect_to root_url
  end
  
  def deck_params
    params.require(:deck).permit(:name, :imagefile_name, :comment, :number_of_use, :number_of_wins)
  end
  
  def correct_user
    @deck = current_user.decks.find_by(id: params[:id])
    unless @deck
      flash[:danger] = "権限がありません"
      redirect_to root_url
    end
  end
  
end

app/views/decks/edit.html.erb
<div class="row">
    <div class="offset-lg-2 col-lg-8">
        <h1 class="mx-auto text-light font-weight-light mt-5 mb-3">デッキ編集</h1>
    </div>
    <div class="bg-light offset-lg-2 col-lg-8 p-4">
        <% @deck.errors.full_messages.each do |message| %>
            <div class="form-error alert alert-danger">
                <%= message %>
            </div>
        <% end %>
        <%= form_with(model: @deck, local: true, multipart: true) do |f| %>
            <div class="form-group">
                <%= f.label :name, 'デッキ名' %>
                <%= f.text_field :name, class: 'form-control' %>
            </div>
            <div class="form-group">
                <%= f.label :imagefile_name, '切り札画像' %>
                <%= f.file_field :imagefile_name, class: 'form-control' %>
            </div>
            <div class="form-group">
                <%= f.label :comment, 'デッキ説明(未入力でも可)' %>
                <%= f.text_area :comment, class: 'form-control' %>
            </div>
            <%= f.hidden_field :number_of_use, :value => @deck.number_of_use.to_i %>
            <%= f.hidden_field :number_of_wins, :value => @deck.number_of_wins.to_i %>
            <%= f.submit '保存', class: 'btn btn-primary btn-block'  %>
        <% end %>
    </div>
</div>

app/views/decks/new.html.erb
<div class="row">
    <div class="offset-lg-2 col-lg-8">
        <h1 class="mx-auto text-light font-weight-light mt-5 mb-3">デッキ登録</h1>
    </div>
    <div class="bg-light offset-lg-2 col-lg-8 p-4">
        <% @deck.errors.full_messages.each do |message| %>
            <div class="form-error alert alert-danger">
                <%= message %>
            </div>
        <% end %>
        <%= form_with(model: @deck, local: true, multipart: true) do |f| %>
            <div class="form-group">
                <%= f.label :name, 'デッキ名' %>
                <%= f.text_field :name, class: 'form-control' %>
            </div>
            <div class="form-group">
                <%= f.label :imagefile_name, '切り札画像' %>
                <%= f.file_field :imagefile_name, class: 'form-control' %>
            </div>
            <div class="form-group">
                <%= f.label :comment, 'デッキ説明(未入力でも可)' %>
                <%= f.text_area :comment, class: 'form-control' %>
            </div>
            <%= f.hidden_field :number_of_use, :value => 0.to_i %>
            <%= f.hidden_field :number_of_wins, :value => 0.to_i %>
            <%= f.submit '登録', class: 'btn btn-primary btn-block'  %>
        <% end %>
    </div>
</div>

app/views/decks/show.html.erb
<div class="row">
    <div class="col-12 col-sm-6 col-lg-5">
        <img src="<%= "#{@deck.imagefile_name}" %>", class = "showcardimage">
    </div>
    <div class="col-12 col-sm-6 col-lg-7">
        <h1 class="text-center text-light mt-5"><%= "#{@deck.name}" %></h1>
        <div class="bg-light border comment">
            <div>
                <p class="p-2 mb-0 text-center"><%= "#{@deck.comment}" %></p>
            </div>
            <%= form_with(model: @deck, local: true) do |f| %>
                <table class="table table-bordered text-center mb-0">
                    <tr>
                        <td class="form-group">
                            <div>
                                <%= f.label :number_of_use, '使用数' %>
                            </div>
                            <div>
                                <%= f.text_field :number_of_use, class: 'form-control' %>
                            </div>
                        </td>
                        <td class="form-group">
                            <div>
                                <%= f.label :number_of_wins, '勝利回数' %>
                            </div>
                            <div>
                                <%= f.text_field :number_of_wins, class: 'form-control' %>
                            </div>
                        </td>
                        <td>
                            <p>勝率</p>
                            <p><%= @rate.round(2) %>%</p>
                            <div>
                                <%= f.submit '計算', class: 'btn btn-primary btn-block'  %>
                            </div>
                        </td>
                    </tr>
                </table>
            <% end %>
        </div>
        <% if current_user.favorited?(@deck) %>
            <%= link_to(deck_favorite_path(@deck.id), {method: :delete, class: "btn btn-danger text-light float-right"}) do %>お気に入り解除<span class="fas fa-star"></span><% end %>
        <% else %>
            <%= link_to(deck_favorites_path(@deck.id), {method: :post, class: "btn btn-primary text-light float-right"}) do %>お気に入り登録<span class="far fa-star"></span><% end %>
        <% end %>
    </div>
</div>
<div class="row mt-4">
    <div class="col-6 col-lg-6">
        <%= link_to("リストに戻る", root_url, class: 'btn btn-primary btn-block' ) %>
    </div>
    <div class="col-3 col-lg-3">
        <%= link_to("編集", edit_deck_path, class: 'btn btn-primary btn-block' ) %>
    </div>
    <div class="col-3 col-lg-3">
        <%= link_to '削除', @deck, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger btn-block' %>
    </div>
</div>